"""review_tables

Revision ID: e2d6fa33415f
Revises: bd5f555b932c
Create Date: 2026-07-18 10:37:34.414633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d6fa33415f'
down_revision: Union[str, None] = 'bd5f555b932c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_node_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('card_type', sa.String(length=20), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('due_at', sa.String(length=30), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_cards_knowledge_node_id'), 'review_cards', ['knowledge_node_id'], unique=False)
    op.create_index(op.f('ix_review_cards_user_id'), 'review_cards', ['user_id'], unique=False)
    op.create_table('review_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('state_before', sa.String(length=20), nullable=False),
    sa.Column('state_after', sa.String(length=20), nullable=False),
    sa.Column('stability_before', sa.Float(), nullable=False),
    sa.Column('stability_after', sa.Float(), nullable=False),
    sa.Column('difficulty_before', sa.Float(), nullable=False),
    sa.Column('difficulty_after', sa.Float(), nullable=False),
    sa.Column('time_spent_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['review_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_events_card_id'), 'review_events', ['card_id'], unique=False)
    op.create_index(op.f('ix_review_events_user_id'), 'review_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_events_user_id'), table_name='review_events')
    op.drop_index(op.f('ix_review_events_card_id'), table_name='review_events')
    op.drop_table('review_events')
    op.drop_index(op.f('ix_review_cards_user_id'), table_name='review_cards')
    op.drop_index(op.f('ix_review_cards_knowledge_node_id'), table_name='review_cards')
    op.drop_table('review_cards')
    # ### end Alembic commands ###
